# Alle hier gesetzten Werte können über `$addon->getProperty($key)` abgefragt werden

package: nv_captcha # Pflichtfeld
version: '1.0' # Pflichtfeld
author: novinet GmbH & Co KG
supportpage: https://github.com/novinet-git/nv_modulesettings

    
# Abhängigkeiten
# Anforderungen ans System oder anderere AddOns, um dieses AddOn installieren oder update zu können
requires:
    redaxo: '>=5.5' # benötigt mindestens REDAXO 5.5
    packages:
        yform: '>=3' # benötigt mindestens das Addon MForm 5.3.1
    php:
        version: '>=5.6' # benötigt mindestens PHP 5.6

